houses = ["Gryffindor",
          "Hufflepuff",
          "Ravenclaw",
          "Slytherin"]

magic = ['Alchemy',
         'Animation',
         'Conjuror',
         'Disintegration',
         'Elemental',
         'Healing',
         'Illusion',
         'Immortality',
         'Invisibility',
         'Invulnerability',
         'Necromancer',
         'Omnipresent',
         'Omniscient',
         'Poison',
         'Possession',
         'Self-Detonation',
         'Summoning',
         'Water-Breathing']

courses = ['Alchemy Basics',
           'Alchemy Advanced',
           'Magic for Day-to-Day Life',
           'Magic for Medical Professionals',
           'Dating with Magic']

student_list = {1: {'first_name': 'hermione',
                    'last_name': 'granger',
                    'created': 1579337616.4544504,
                    'last_updated': 1578824704,
                    'current_magic': ['Alchemy 1', 'Possession 2', 'Invisibility 3', 'Invulnerability 4', 'Necromancer 5'],
                    'desired_magic': ['Immortality 5', 'Elemental 4'],
                    'desired_course': ['Alchemy Advanced', 'Magic for Day-to-Day Life'],
                    'house': "Gryffindor"
                    },
                2: {'first_name': 'harry',
                    'last_name': 'potter',
                    'created': 1579337616.4544504,
                    'last_updated': 1578846041,
                    'current_magic': ['Alchemy 1', 'Possession 4', 'Self-detonation 3', 'Summoning 2', 'Water-Breathing 1'],
                    'desired_magic': ['Invisibility 5', 'Healing 4'],
                    'desired_course': ['Alchemy Advanced', 'Dating with Magic'],
                    'house': "Gryffindor"
                    },
                3: {'first_name': 'ron',
                    'last_name': 'weasley',
                    'created': 1579337616.4544504,
                    'last_updated': 1579533943,
                    'current_magic': ['Animation 2', 'Conjuror 2', 'Necromancer 2', 'Omnipresent 2', 'Omniscient 2'],
                    'desired_magic': ['Possession 3', 'Alchemy 5'],
                    'desired_course': ['Alchemy Basics', 'Magic for Day-to-Day Life'],
                    'house': "Gryffindor"
                    },
                4: {'first_name': 'albus',
                    'last_name': 'Dumbledore',
                    'created': 1282293045,
                    'last_updated': 1448444743,
                    'current_magic': ['Immortality 5', 'Invulnerability 5', 'Summoning 5', 'Illusion 5', 'Omniscient 5'],
                    'desired_magic': ['Possession 3', 'Alchemy 5'],
                    'desired_course': ['Alchemy Advanced', 'Magic for Day-to-Day Life'],
                    'house': "Gryffindor"
                    },
                5: {'first_name': 'newt',
                    'last_name': 'scamander',
                    'created': 1579337616.4544504,
                    'last_updated': 1451737420,
                    'current_magic': ['Summoning 4', 'Disintegation 2', 'Elemental 4', 'Healing 5', 'Poison 2'],
                    'desired_magic': ['Water-Breathing 4', 'Alchemy 5'],
                    'desired_course': ['Alchemy Advanced', 'Dating with Magic'],
                    'house': "Hufflepuff"
                    },
                6: {'first_name': 'rubeus',
                    'last_name': 'hagrid',
                    'created': 1579337616.4544504,
                    'last_updated': 1451737420,
                    'current_magic': ['Possession 4', 'Self-Detonation 2', 'Summoning 4', 'Water-Breathing 5', 'Poison 2'],
                    'desired_magic': ['Water-Breathing 4', 'Alchemy 5'],
                    'desired_course': ['Alchemy Advanced', 'Dating with Magic'],
                    'house': "Gryffindor"
                    },
                7: {'first_name': 'cedric',
                    'last_name': 'diggory',
                    'created': 1579337616.4544504,
                    'last_updated': 1451737420,
                    'current_magic': ['Alchemy 4', 'Animation 2', 'Conjuror 4', 'Disintegration 5', 'Elemental 2'],
                    'desired_magic': ['Water-Breathing 4', 'Alchemy 5'],
                    'desired_course': ['Alchemy Advanced', 'Dating with Magic'],
                    'house': "Hufflepuff"
                    }
                }
